config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Routes to homeapage
  root to: 'pages#home'
  resources :posts, only: [:index, :new, :create, :show] do
    # This route will coming later
    resources :comments, only: [:index, :create]
    # upvote feature
    member do
      put "like" => "posts#vote"
    end
    # bookmark feature
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Routes to main map
  get 'bookmarks/update'
  get "map", to: "maps#show", as: :map
  # get "posts/:id", to: "posts#show", as: :post
  get "dashboard/:id", to: "pages#show", as: :dashboard
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, presence: true
  validates :content, presence: true, length: { maximum: 280 }

end

app/models/post.rb
class Post < ApplicationRecord
  DEFAULT_PHOTO_URL = ""

  acts_as_votable
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  mount_uploader :photo, PhotoUploader
  validates :content, presence: true
  validates :content, presence: true, length: { maximum: 280 }

  after_create :broadcast_to_map

  def photo
    super.present? || self.new_record? ? super : DEFAULT_PHOTO_URL
  end

  def navigation_url
    "http://maps.google.com.au/maps?daddr=(#{latitude},#{longitude})"
  end

  private

  def broadcast_to_map
    post_marker = {
      url: "/posts/#{id}",
      user: {
        name: user.username,
        photo: {
          url: user.photo.url
        }
      },
      id: id,
      longitude: longitude,
      latitude: latitude,

      time: "just now",
      title: title,
      content: content,
      post_photo: photo.url
    }
    MapChannel.broadcast_to(0, post_marker)
  end
end

app/models/post_upvote.rb
class PostUpvote < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/upvote.rb
class Upvote < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_voter
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  mount_uploader :photo, PhotoUploader
  validates :photo, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :photo])
  end

  # create helper method
  def bookmark_text
    @bookmark_exists ? '<i class="fas fa-bookmark"></i>' : '<i class="far fa-bookmark"></i>'
  end

  helper_method :bookmark_text
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def update
    # checks if favourite exists
    @bookmark = Bookmark.where(post: Post.find(params[:post]), user: current_user) # output is array
    if @bookmark === []
      # create bookmark
      Bookmark.create(post: Post.find(params[:post]), user: current_user)
      @bookmark_exists = true
    else
      # delete favourite
      @bookmark.destroy_all
      @bookmark_exists = false
    end

    # page render
    respond_to do |format|
      format.html {}
      format.js {}
    end

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments

    @new_comment = Comment.new()
    @new_comment.post = @post
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.user = current_user
    if @comment.save
      respond_to do |format|
        format.html { redirect_to post_path(@post) }
        format.js # <-- will render `app/views/comments/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'posts/show' }
        format.js # <-- idem
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def show
    @posts = Post.all
    # @markers = @posts.map do |post|
    #   {
    #     lat: post.latitude,
    #     lng: post.longitude,
    #     infoWindow: render_to_string(partial: "posts/info_window", locals: { post: post })
    #   }
    # end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def show
    @user = current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:vote]
  before_action :set_post, only: [:show, :vote]
  respond_to :js, :json, :html # respond to JS on all actions

  def index
    latMin = params[:latMin]
    latMax = params[:latMax]
    lngMin = params[:lngMin]
    lngMax = params[:lngMax]
    @posts = Post.where(["latitude > ?", latMin])
                 .where(["latitude < ?", latMax])
                 .where(["longitude > ?", lngMin])
                 .where(["longitude < ?", lngMax])
    respond_to do |format|
      format.html
      @post_markers = @posts.map do |post|
        {
          time: "#{helpers.distance_of_time_in_words(Time.current - post.created_at)} ago",
          title: post.title,
          content: post.content,
          post_photo: post.photo.url(:small_card),
          id: post.id,
          url: post_path(post),
          latitude: post.latitude,
          longitude: post.longitude,
          user: {
            name: post.user.username,
            photo: post.user.photo
          }
        }
      end
      format.json { render json: @post_markers }
    end
  end

  def show
    set_post
    @bookmark_exists = Bookmark.where(post: @post, user: current_user) ==   [] ? false : true
  end

  def new
    @post = Post.new
    @post.user = current_user
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      respond_to do |format|
        format.html { redirect_to map_path }
        format.js
      end
    else
      render :new
    end
  end

  def vote # naming of action is important
    if !current_user.liked? @post
      @post.liked_by current_user # like post if it has not been liked
    elsif current_user.liked? @post
      @post.unliked_by current_user # unlike post if it has already been liked
    end
  end

  private

  def post_params
    params.require(:post).permit(:content, :photo, :latitude, :longitude, :title)
  end

  def set_post
    @post = Post.find(params[:id])
    @comment = Comment.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookmarks/update.js.erb
var bookmarkBtnEl = document.querySelector("#btn-bookmark");
console.log("fire")
bookmarkBtnEl.innerHTML = '<%= raw bookmark_text %>'; // to allow for HTML injections

app/views/comments/_card-content.html.erb
<%= render 'comments/form', comment: @new_comment, post: @new_comment.post  %>
<div id="comments" class="my-2">
  <% @comments.each do |comment| %>
    <%= render 'comments/show', comment: comment %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<div>

  <div class="form-create-post">
    <%= simple_form_for([ post, comment ], remote: true) do |form| %>
      <!-- flex box input field and button -->
      <div class="form-create-post-inner">
        <%= form.input :content, label: false, input_html: { class: 'input-comment-content' }, placeholder: "Add a comment" %>
        <%= form.submit "Post", class: 'post-comment-btn' %>
      </div>
    <% end %>
  </div>

<!--   <p class="my-2" style="font-size: 20px;font-weight: 300;"> Comments Section: </p>
 --></div>

app/views/comments/_show.html.erb
<div class="comment-box">
  <%= cl_image_tag comment.user.photo, height: 50, width: 50, crop: :fill %>
  <div class="comment-info">
    <p><small><%= comment.user.username %></small></p>
    <p class="pb-2"><%= comment.content %></p>
    <p class="pb-1"><small><%= distance_of_time_in_words(Time.current - comment.created_at) %></small></p>
  </div>
</div>

app/views/comments/create.js.erb
function refreshForm(innerHTML) {
  const newCommentForm = document.getElementById('new_comment');
  newCommentForm.innerHTML = innerHTML;
}

function addComment(commentHTML) {
  const comments = document.getElementById('comments');
  comments.insertAdjacentHTML('afterbegin', commentHTML);
}

// <%= @comment.errors.first %>

<% if @comment.errors.any? %>
  refreshForm('<%= j render "comments/form", post: @post, comment: @comment %>');
<% else %>
  addComment('<%= j render "comments/show", comment: @comment %>');
  refreshForm('<%= j render "comments/form", post: @post, comment: Comment.new %>');
<% end %>

app/views/comments/index.html.erb
Test

app/views/comments/index.js.erb
var showHTML = "<%= j render 'card-content' %>";

generalModal.find('.js-post-card-content')
            .html(showHTML);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Wing-It</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable"  content="yes">
     <%= render 'shared/ios_pwa_links' %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
  </head>
  <body>
    <!-- navbar -->
    <!-- flash  messages -->
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render 'posts/form_animation' %>
    <%= render 'shared/modal' %>
  </body>
</html>

app/views/maps/map.html.erb
<h1>Map</h1>

app/views/maps/show.html.erb
<div>
  <%= render 'shared/navbar' %>
  <div
    id="map"
    style="width: 100%;
    position: absolute;
    top: 0;
    right: 0;
    z-index: -1;
    height: 100%;"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  <div class="card-container js-post-container">
  </div>
  <div class="map-loading js-map-loading">
    <div id="loading-wave ">
      <span class="fas fa-globe-asia loading-dot fa-spin"></span>
      <span class="loading-dot">L</span>
      <span class="loading-dot">O</span>
      <span class="loading-dot">A</span>
      <span class="loading-dot">D</span>
      <span class="loading-dot">I</span>
      <span class="loading-dot">N</span>
      <span class="loading-dot">G</span>
      <span class="loading-dot"> </span>
      <span class="loading-dot">M</span>
      <span class="loading-dot">A</span>
      <span class="loading-dot">P</span>
      <span class="loading-dot">.</span>
      <span class="loading-dot">.</span>
      <span class="loading-dot">.</span>
    </div>
  </div>

  <div class="new-post-button js-new-post-button d-none">
    <%= link_to "+", new_post_path, class: 'btn', remote: true %>
  </div>
</div>

app/views/pages/home.html.erb
<section class="home__container">
    <section class="section hero__banner">
    <%= render 'shared/navbar'%>
        <div class="banner__text">
            <div>
                <p>Travel for the <br>unplanned</p>
                <%= link_to "Explore the map", map_path, class: "btn__explore"  %>
                <%# <div class="arrow__container">
                    <i class="fas fa-long-arrow-alt-down down"></i>
                </div> %>
            </div>
        </div>
        <div class="hero__banner--image">
            <img src="https://images.unsplash.com/photo-1484804959297-65e7c19d7c9f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1914&q=80">
        </div>
    </section>

    <section class="section section__about">
        <div class="banner__text">
             <div>
                <p>Take the stress<br>out of travel
                </p>
                <%= link_to "Explore the map", map_path, class: "btn__explore"  %>
            </div>
        </div>
        <div class="composition">
            <img src="https://images.unsplash.com/photo-1515552726023-7125c8d07fb3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1567&q=80" alt="" class="composition__photo composition__photo--p1">
            <img src="https://images.unsplash.com/photo-1517842264405-72bb906a1936?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2850&q=80" alt="" class="composition__photo composition__photo--p2">
            <img src="https://images.unsplash.com/photo-1533243216203-8c08406d4583?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1951&q=80" alt="" class="composition__photo composition__photo--p3">
        </div>
    </section>

    <section class="section section__discover">
            <div>
                <p class="section__discover--heading">Sign up and start discovering now</p>
            </div>
            <div class="discover__cards--container">
                <div class="discover__cards">
                    <div class="discover__info">
                        <i class="fas fa-globe discover__icons"></i>
                        <h3>Explore</h3>
                    </div>
                    <p>Discover the map for <br>activities near you</p>
                </div>
                <div class="discover__cards">
                    <div class="discover__info">
                        <i class="fas fa-globe discover__icons"></i>
                        <h3>Connect</h3>
                    </div>
                    <p>Discover the map for <br>activities near you</p>
                </div>
                <div class="discover__cards">
                    <div class="discover__info">
                        <i class="fas fa-globe discover__icons"></i>
                        <h3>Inspire</h3>
                    </div>
                    <p>Discover the map for <br>activities near you</p>
                </div>
            </div>
    </section>

    <section class="section section__signup">
         <div class="banner__text signup__text">
             <div>
                <h2>JOIN THE COMMUNITY</h2>
                <p>Sign up and start discovering now</p>
                <%= link_to "Sign up", map_path, class: "btn__explore"  %>
            </div>
            <div class="sign__image">
                <img src="https://images.unsplash.com/photo-1507608443039-bfde4fbcd142?ixlib=rb-1.2.1&auto=format&fit=crop&w=934&q=80">
            </div>
        </div> 
    </section>

    <section class="section section__footer">
        <div class="footer__text">
            <p>&copy; 2019 by Wing It. All rights reserved.</p>
        </div>
    </section>


</div>

app/views/pages/show.html.erb
<%= render 'shared/navbar' %>
<div class="dashboard">

  <div class="dashboard-nav">
      <%= cl_image_tag current_user.photo, crop: :fill, class:"mt-4", style:"height: 80px; width: 80px;" %>
      <h1><%= current_user.username.capitalize %></h1>
  </div>
  <ul class="nav nav-tabs md-tabs" id="myTabMD" role="tablist">
    <li class="nav-item">
      <a class="nav-link" id="home-tab-md" data-toggle="tab" href="#home-md" role="tab" aria-controls="home-md"aria-selected="true">POSTS</a>
    </li>

    <li class="nav-item">
      <a class="nav-link" id="profile-tab-md" data-toggle="tab" href="#profile-md" role="tab" aria-controls="profile-md" aria-selected="false">BOOKMARKS</a>
    </li>
  </ul>


  <div class="tab-content p-4" id="myTabContentMD">
    <!-- POSTS -->
    <div class="tab-pane fade show active" id="home-md" role="tabpanel" aria-labelledby="home-tab-md">
      <% current_user.posts.each do |post| %>
        <%= link_to post_path(post), class: 'dashboard-card mb-4', remote: true do %>
          <img src=" <%= cl_image_path post.photo, crop: :fill %>" alt="post-image">
          <div class="dashboard-card-content">
              <span class="flex-grow-1"><i class="fas fa-fire fire-count" style="color: #df5715;"> <span style="font-family: Roboto; font-weight: 400;"><%= post.get_upvotes.size %></span></i></span>
              <p><%= post.created_at.strftime("Posted on: %m/%d/%Y")%></p>
          </div>
        <% end %>
      <% end %>

    </div>
    <!-- BOOKMARKS -->
    <div class="tab-pane fade active" id="profile-md" role="tabpanel" aria-labelledby="profile-tab-md">
      <% current_user.bookmarks.each do |bookmark| %>
        <%= link_to post_path(bookmark.post.id), class: 'dashboard-card mb-4', remote: true do %>
          <img src="<%= cl_image_path bookmark.post.photo, crop: :fill %>" alt="post-image">
          <div class="dashboard-card-content d-flex align-items-center">
                <div class="d-flex flex-wrap">
                <span><i class="far fa-user-circle user-icon"></i></span>
                <h2><%= bookmark.post.user.username %></h2>
                </div>
                <p><%= bookmark.post.created_at.strftime("Posted: %m/%d/%Y") %></p>
          </div>
        <% end %>
      <% end %>
    </div>

  </div>
</div>

app/views/posts/_card.html.erb
<div class="card-large" style="position: relative; background-image: linear-gradient(0deg, rgba(0,0,0,1), rgba(0,0,0,0.9), rgba(0,0,0,0.7),rgba(0,0,0,0.6),rgba(0,0,0,.4),rgba(0,0,0,.2),rgba(0,0,0,0)), url(<%= cl_image_path(@post.photo, height: 350, width: 350, crop: :fill) %>)">
    <div class="card-large-infos d-flex flex-column">
      <div class="directions-btn">
        <%= link_to @post.navigation_url do %>
          <i class="fas fa-directions"></i>
        <% end %>
      </div>

      <!-- div containing ICONS -->
      <div class="icon-large-card-container align-self-start">
        <!-- upvote icon -->
        <div class="btn-like">
          <%= link_to like_post_path(@post), class:"like-btn", method: :put, remote: :true do %>
            <i class="fas fa-fire"> <span class="like-count" style="color: white; font-family: Roboto; font-weight: normal;"><%= @post.get_upvotes.size %></span></i>
          <% end %>
        </div>

        <!-- comment icon -->
        <div class="comment-btn">
          <%= link_to post_comments_path(@post), remote: true do %>
            <i class="far fa-comment"></i>
          <% end %>
        </div>

        <!-- info button -->
        <div class="back-to-post-btn">
          <%= link_to post_path(@post), remote: true do %>
            <i class="fas fa-chevron-left"></i>
          <% end %>
        </div>

        <!-- bookmark button -->
        <div class="i-bookmark">
          <%= link_to bookmarks_update_path(post: @post), id:"btn-bookmark", remote: :true do %>
            <%= raw bookmark_text %> <!-- to allow for HTML injections -->
          <% end %>
        </div>

      </div>

      <!-- username and content -->
      <div class="js-post-card-content container-username-content">

        <div class="d-flex justify-content-between align-items-center my-3">
          <!-- username -->
          <h2 class="js-username username-lg-card">
            <i class="far fa-user-circle"></i>
            <%= @post.user.username %>
          </h2>
          <!-- Time -->
          <div class="i-time">
            <i class="far fa-clock"></i>
            <%= distance_of_time_in_words(Time.current - @post.created_at)%> ago
          </div>
        </div>
        <!-- content -->
        <p class="js-post-content mb-1 post-content"><%= @post.content %></p>
      </div>

  </div>
</div>

app/views/posts/_form.html.erb
<!-- <div class="p-3 post-form-card js-create-post-form" style="border-radius: 15px; position: relative; background-image: linear-gradient(rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7)), url('https://images.unsplash.com/photo-1475688621402-4257c812d6db?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=3367&q=80'); background-size: cover; margin: auto;"> -->
<div class="js-create-post-form create-post-form">
  <%= simple_form_for post, remote: true do |f| %>
    <%= f.input :latitude, input_html: {class: "js-create-post-lat"}, wrapper_html: { class: 'd-none'}, as: :hidden %>
    <%= f.input :longitude, input_html: {class: "js-create-post-lon"}, wrapper_html: { class: 'd-none'}, as: :hidden %>

    <div class="create-post-form-step-image">
      <img class="js-post-form-upload-preview create-post-form-preview d-none" />
      <%= f.input :photo, input_html: { class: "js-post-form-image-field" }, label_html: { class: 'create-post-form-upload-button' }, wrapper_html: { class: 'js-post-form-image-wrapper mb-0'}, label: "UPLOAD PHOTO" %>
      <input type="file" accept="image/*" id="capture" capture="camera">
      <%= f.input :photo_cache, as: :hidden, wrapper_html: { class: 'd-none' } %>
    </div>
    <div class="create-post-form-step-content">
      <%= f.input :content, id:"make-post-content-text", label: false, placeholder: 'Write somethin\'...' %>
      <%= f.submit "Post", class: "btn-make-post js-create-post-button" %>
    </div>

    <div class="js-create-post-actions d-none">
      <div class="js-create-post-loading" style="color: white;"><span class="fa fa-spinner fa-spin"></span> Getting your location...</div>
      <!-- <div class="js-location-message"></div> -->
    </div>
  <% end %>
</div>

app/views/posts/_info_window.html.erb
<div style="position: relative;">
  <%= link_to "", post_path(post), class: "clickable" %>
  <%= cl_image_tag post.user.photo, height: 60, width: 60, :radius=>50, crop: :fill %>
  <p class="text"><%= post.content %></p>
  <p>Posted by: <strong><%= post.user.username %></p></strong>
  <p>Posted: <strong><%= distance_of_time_in_words(Time.current - post.created_at) %> ago</strong></p>
</div>

app/views/posts/create.js.erb
// End the loading status
// Close post new window
console.log("Just finished sending stuff")
mainMap.mainPopup.remove();

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div>
    <%= post.content %>
    <%= post.latitude %>
    <%= post.longitude %>
  </div>
  <hr>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/navbar' %>
<%= render 'form', post: @post %>

app/views/posts/new.js.erb
var formHTML = "<%= j render 'form', post: @post %>";

mainMap.addCreateFormToMap(formHTML);

// generalModal.find('.modal-content')
//             .html(formHTML);

// generalModal.modal("show");

app/views/posts/show.html.erb
<%= render 'shared/navbar' %>

<br>
<!-- Comments -->
  <div id="comments">
    <% if @post.comments.blank? %>
      <%= render 'comments/form', post: @post, comment: @comment %>
    <% else %>
      <% @post.comments.each do |comment| %>
        <%= render 'comments/show', comment: comment %>
      <% end %>
    <% end %>
  </div> <!-- comments -->

<%= render 'comments/form', post: @post, comment: @comment %>


  <!-- Bookmark button -->

  <%= link_to "See your dashboard", dashboard_path(current_user) %>
  <%= link_to 'Keep Exploring!', map_path  %>

<div class="card-large" style="position: relative;">
  <a href class="clickable js-post-link"></a>
  <%= cl_image_tag @post.photo, height: 350, width: 350, crop: :fill %>
  <div class="card-large-infos">
    <div>
      <div class="icon-large-card">

        <div class="icon-large-card-container">
        <!-- upvote icon -->
          <div>
            <%= link_to like_post_path(@post), class:"like-btn", method: :put, remote: :true do %>
              <i class="fas fa-thumbs-up"> <span class="like-count" style="color: white; font-family: Roboto; font-weight: normal;"><%= @post.get_upvotes.size %></span></i>
            <% end %>
          </div>

          <!-- upvote -->

          <div>
            <%= link_to post_comments_path(@post), remote: true do %>
              <i class="far fa-comment"></i>
            <% end %>
          </div>
          <div class="icon-info">
            <%= link_to post_path(@post), remote: true do %>
              <i class="fa fa-info"></i>
            <% end %>
          </div>

          <div class="i-bookmark"><%= link_to bookmarks_update_path(post: @post), id:"btn-bookmark", remote: :true do %>
            <%= raw bookmark_text %> <!-- to allow for HTML injections -->
          <% end %>
          </div>

        </div>

      <h2 class="js-username"><%= @post.user.username %></h2>
<%= render 'comments/form', post: @post, comment: @comment %>
      <div class="i-time"><i class="far fa-clock"></i>
        <%= distance_of_time_in_words(Time.current - @post.created_at)%> ago
      </div>
    </div>

      </div>


    <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-large-user avatar-bordered js-user-avatar" />
  </div>
</div>

app/views/posts/show.js.erb
var showHTML = "<%= j render 'card', post: @post %>";

generalModal.find('.modal-content')
            .html(showHTML);

generalModal.modal("show");

app/views/posts/vote.js.erb
var likeBtnEl = document.querySelector(".like-btn"); // needs to be var
var likeCountEl = document.querySelector(".like-count"); // needs to be var

<% if current_user.liked? @post %>
  likeBtnEl.classList.add("liked") // adds 'like' class to upvote button
<% else %>
  likeBtnEl.classList.remove("liked") // adds 'like' class to upvote button
<% end %>
  // $('.likes-count').html("<%= @post.get_upvotes.size %>")
likeCountEl.innerHTML = "<%= @post.get_upvotes.size %>"

app/views/shared/_card_overlay.html.erb
<div class="card-overlay">

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
  </button>



  <div class="collapse navbar-collapse border-0" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link", style: "color: white;" %>
        </li>
        <li class="nav-item mb-1">
          <%= link_to "Dashboard", dashboard_path(current_user), class: "nav-link", style: "color: white;" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link", style: "color: white;" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>